In [122]:
# Import Important libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [123]:
# Read Dataset
data = pd.read_csv("netflix_titles.csv")

In [124]:
# Read First 3 Rows From Dataset
data.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [125]:
# Read Last 3 Rows From Dataset
data.tail(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [126]:
# Information about Dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [127]:
data['rating'].head(2)

0    PG-13
1    TV-MA
Name: rating, dtype: object

In [128]:
data['show_id'].head(3)

0    s1
1    s2
2    s3
Name: show_id, dtype: object

In [129]:
data['date_added'].head(3)

0    September 25, 2021
1    September 24, 2021
2    September 24, 2021
Name: date_added, dtype: object

In [130]:
data.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [131]:
data.shape

(8807, 12)

In [132]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8802    False
8803    False
8804    False
8805    False
8806    False
Length: 8807, dtype: bool

In [133]:
data.duplicated().sum()

0

In [134]:
data.isna()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,False,False,False,False,True,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False,False,False
3,False,False,False,True,True,True,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,False,False,False,False,False,False,False,False,False,False,False,False
8803,False,False,False,True,True,True,False,False,False,False,False,False
8804,False,False,False,False,False,False,False,False,False,False,False,False
8805,False,False,False,False,False,False,False,False,False,False,False,False
8806,False,False,False,False,False,False,False,False,False,False,False,False

In [135]:
data.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [136]:
data.isna().sum().sum() # Total Numbers of NaN Values

4307

In [137]:
data.dropna(inplace = True)

In [138]:
data.shape

(5332, 12)

In [139]:
new_columns_name = []
for i in data.columns:
    new_columns_name.append(i.capitalize())
new_columns_name 
data.columns = new_columns_name

In [140]:
data.columns

Index(['Show_id', 'Type', 'Title', 'Director', 'Cast', 'Country', 'Date_added',
       'Release_year', 'Rating', 'Duration', 'Listed_in', 'Description'],
      dtype='object')

In [141]:
data['Show_id'].unique()

array(['s8', 's9', 's10', ..., 's8805', 's8806', 's8807'], dtype=object)

In [142]:
data['Show_id'].nunique()

5332

In [143]:
data['Show_id'] = data['Show_id'].apply(lambda x : x.split("s")[1])

In [144]:
data['Show_id'][12]

'13'

In [145]:
type(data['Show_id'][12])

str

In [146]:
data["Show_id"] = data["Show_id"].astype(int)
data["Show_id"]

7          8
8          9
9         10
12        13
24        25
        ...
8801    8802
8802    8803
8804    8805
8805    8806
8806    8807
Name: Show_id, Length: 5332, dtype: int32

In [147]:
type(data['Show_id'][12])

numpy.int32

In [148]:
data['Date_added'] = pd.to_datetime(data['Date_added'], errors='coerce')

In [149]:
type(data['Date_added'])

pandas.core.series.Series

In [150]:
data['Date_added'].isna().sum()

4

In [151]:
# Replace empty values ​​with the first day of the data
data['Date_added'].fillna(pd.Timestamp('2015-01-01'), inplace=True)

C:\Users\FLASH ON LINE\AppData\Local\Temp\ipykernel_13644\3876244198.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Date_added'].fillna(pd.Timestamp('2015-01-01'), inplace=True)